### ISSUE TITLE
Clarification about LICENSE

### ISSUE THREAD

**Issue by itayplav** [essalguero/EmpaticaBLEServerMock#1]
Hello, I'm looking to clarify what license this project is released under? Thanks!

**Comment by essalguero** [comment]
I will include in the repo a copy of the GNU GPL v3 license

**Comment by itayplav** [comment]
Cheers, if it's also possible to add the binary executable to the release files that would make it easier to quickly get the mock serving up and running. I've attached the executable I built on my machine for convenience but you might prefer to build it yourself. Thanks for this tool!
[EmpaticaBLEServerMock.zip](https://github.com/essalguero/EmpaticaBLEServerMock/files/5752817/EmpaticaBLEServerMock.zip)

**Comment by essalguero** [comment]
Hi again:

Unfortunately, I cannot put the GNU GPL v3 license in the project. 

Originally, this was developed as an internal testing tool for a project made for the "Fundación Orange" in Spain. Someone made the smart decision to deliver this test tool as part of the project and therefore, the code now is supposed to belong to "Fundación Orange".

I'm sorry about the confusion


Best regards
